/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.robertpyke.regexmatcher;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int Button01=0x7f05000f;
        public static final int InputCheck=0x7f05000c;
        public static final int InputCheckPrompt=0x7f05000b;
        public static final int InputRegex=0x7f050009;
        public static final int InputRegexPrompt=0x7f050008;
        public static final int LinearLayout01=0x7f050005;
        public static final int Output=0x7f05000e;
        public static final int OutputPrompt=0x7f05000d;
        public static final int TableLayout01=0x7f050006;
        public static final int TableRow01=0x7f050007;
        public static final int TableRow02=0x7f05000a;
        public static final int helpScrollView=0x7f050000;
        public static final int helpTextView=0x7f050001;
        public static final int infoScrollView=0x7f050002;
        public static final int infoTextView=0x7f050003;
        public static final int mainScrollView=0x7f050004;
    }
    public static final class layout {
        public static final int help=0x7f030000;
        public static final int info=0x7f030001;
        public static final int main=0x7f030002;
    }
    public static final class string {
        public static final int app_description=0x7f040001;
        public static final int app_name=0x7f040000;
        public static final int email=0x7f040004;
        public static final int help_label=0x7f040007;
        public static final int help_text=0x7f040009;
        public static final int home_page=0x7f040003;
        public static final int info_label=0x7f040008;
        public static final int main_label=0x7f040006;
        public static final int support_message=0x7f040005;
        public static final int version=0x7f040002;
    }
}
